---
title: "Introduccion"
output:
  md_document:
    variant: markdown_github
vignette: >
  %\VignetteIndexEntry{Introduccion}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Accediendo a los datos

```{r}
library(plebiscito2020)
library(dplyr)
head(constitucion)
```

## Agregación datos usando `dplyr`
```{r}
constitucion %>% group_by(opcion) %>% summarize(total_votos = sum(votos, na.rm = TRUE))
```

```{r}
constitucion %>% group_by(nombre_comuna, opcion) %>% summarize(total_votos = sum(votos, na.rm = TRUE))
```

```{r}
head(tipo_de_organo)
```


```{r}
tipo_de_organo %>% group_by(opcion) %>% summarize(total_votos = sum(votos, na.rm = TRUE))
```

```{r}
tipo_de_organo %>% group_by(nombre_comuna, opcion) %>% summarize(total_votos = sum(votos, na.rm = TRUE))
```

### Construyendo la base de datos 

```{r}
circ_electoral_df <- circ_electoral("elecciones_constitucion")
head(circ_electoral_df)
```


```{r}
mesas_df <- data.frame()
for(i in 1:nrow(circ_electoral_df)){ 
             res <- mesas_circ_electoral("elecciones_constitucion",
                                       circ_electoral_df[i,"id_circ_electoral"])
             mesas_df <- bind_rows(mesas_df, res)
        }
head(mesas_df)
```

```{r}
resultado_mesa("elecciones_constitucion", 71030001)
```


```{r}
resultado_mesa("elecciones_constitucion", 71030001)$data
```

```{r}
resultado_mesa("elecciones_constitucion", 71030001)$resumen
```

```{r}
resultado_mesa("elecciones_convencion", 71030001)$data
resultado_mesa("elecciones_convencion", 71030001)$resumen
```


## Obtener el resultado de todas las mesas

```{r}
sel_columnas <- function(resultado){
  sel <- resultado[, c("a","c")]
  names(sel) <- c("opcion", "votos")
  sel$votos <- as.numeric(sel$votos)
  return(sel)
}
```

```{r}
id_mesas <- mesas$id_mesa
datos_mesas_con <-  data.frame()
datos_mesas_con_val <-  data.frame()
datos_mesas_org <-  data.frame()
datos_mesas_org_val <-  data.frame()
for(i in 1:5){   #solo las 5 priemras mesas
  mesa <- id_mesas[i]
  res_mesa  <- sel_columnas(resultado_mesa("elecciones_constitucion", mesa)$data)
  res_mesa <- cbind(id_mesa = mesa, res_mesa)
  datos_mesas_con <- bind_rows(datos_mesas_con, res_mesa)
  
  res_mesa  <- sel_columnas(resultado_mesa("elecciones_constitucion", mesa)$resumen)
  res_mesa <- cbind(id_mesa = mesa, res_mesa)
  datos_mesas_con_val <- bind_rows(datos_mesas_con_val, res_mesa)
  
  res_mesa  <- sel_columnas(resultado_mesa("elecciones_convencion", mesa)$data)
  res_mesa <- cbind(id_mesa = mesa, res_mesa)
  datos_mesas_org <- bind_rows(datos_mesas_org, res_mesa)
  
  res_mesa  <- sel_columnas(resultado_mesa("elecciones_convencion", mesa)$resumen)
  res_mesa <- cbind(id_mesa = mesa, res_mesa)
  datos_mesas_org_val <- bind_rows(datos_mesas_org_val, res_mesa)
  
}      
resultados <- list(apruebo_rechazo = datos_mesas_con,
                   apruebp_rechazo_val = datos_mesas_con_val,
                   tipo_organo = datos_mesas_org, 
                   tipo_organo_val = datos_mesas_org_val)

resultados$apruebo_rechazo
resultados$apruebp_rechazo_val
resultados$tipo_organo
resultados$tipo_organo_val

```

